apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mongo_deployment.yaml
  - mongo_service.yaml
  - mongo_pvc.yaml
  - shopfront_deployment.yaml
  - shopfront_service.yaml
  - product_catalogue_deployment.yaml
  - product_catalogue_service.yaml
  - stock_manager_deployment.yaml
  - stock_manager_service.yaml
  - user_profile_deployment.yaml
  - user_profile_service.yaml
  - ingress.yaml
  - configmap.yaml