apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-manager
  template:
    metadata:
      labels:
        app: stock-manager
    spec:
      containers:
      - name: stock-manager
        image: stock-manager:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/ecommerce"
        livenessProbe:
          httpGet:
            path: /api/stock/health
            port: 5002
          initialDelaySeconds: 5
          periodSeconds: 10